apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: themes/ananke
    contents:
      - path: .
        git:
          url: https://github.com/theNewDynamic/gohugo-theme-ananke.git
          ref: v2.10.0
